INSERT INTO news (title, subtitle, content, category, date, time, image, author, tags, featured, breaking, status, links)
VALUES 
  (
    'Inauguración del Nuevo Hospital Regional',
    'Una obra esperada por más de 10 años',
    'El presidente regional inauguró hoy las modernas instalaciones del hospital que beneficiará a más de 500,000 habitantes. Cuenta con equipos de última generación...',
    'Región',
    '04 de Febrero, 2026',
    '10:30',
    'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&q=80',
    'Carlos Méndez',
    ARRAY['Salud', 'Obras', 'Inauguración'],
    false,
    true,
    'published',
    '[]'::jsonb
  ),
  (
    'Crisis Hídrica: Agricultores Piden Ayuda',
    'La sequía afecta a más del 60% de los cultivos',
    'Representantes del sector agrario se reunieron con autoridades locales para exigir medidas urgentes ante la falta de lluvias que amenaza la campaña de este año...',
    'Nacionales',
    '03 de Febrero, 2026',
    '08:15',
    'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80',
    'María Gómez',
    ARRAY['Agricultura', 'Clima', 'Protesta'],
    false,
    false,
    'published',
    '[]'::jsonb
  ),
  (
    'El Turismo Crece un 15% este Verano',
    'Playas del norte son las más visitadas',
    'El Ministerio de Turismo reportó cifras alentadoras para el sector. La ocupación hotelera en Tumbes y Piura alcanzó niveles históricos durante el mes de enero...',
    'Economía',
    '02 de Febrero, 2026',
    '14:20',
    'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80',
    'Ricardo Alva',
    ARRAY['Turismo', 'Verano', 'Economía'],
    true,
    false,
    'published',
    '[]'::jsonb
  ),
  (
    'Triunfo Histórico de la Selección de Vóley',
    'Clasifican al mundial después de 12 años',
    'En un partido vibrante, el equipo nacional venció a Brasil por 3 sets a 2. La capitana del equipo destacó el esfuerzo y la disciplina del grupo...',
    'Deportes',
    '01 de Febrero, 2026',
    '18:45',
    'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?auto=format&fit=crop&q=80',
    'Sofía Pineda',
    ARRAY['Vóley', 'Selección', 'Victoria'],
    false,
    true,
    'published',
    '[]'::jsonb
  ),
  (
    'Nuevas Tecnologías para la Educación Rural',
    'Tablets con internet satelital llegan a la sierra',
    'El programa "Conectados" entregó hoy 5,000 dispositivos a escolares de zonas alejadas. Se espera reducir la brecha digital en un 20% para finales de año...',
    'Nacionales',
    '31 de Enero, 2026',
    '09:00',
    'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?auto=format&fit=crop&q=80',
    'Juan Pérez',
    ARRAY['Educación', 'Tecnología', 'Inclusión'],
    false,
    false,
    'published',
    '[]'::jsonb
  ),
  (
    'Feria Gastronómica "Sabores del Valle"',
    'Este fin de semana en la plaza principal',
    'Más de 50 expositores presentarán lo mejor de la cocina local. Habrá concursos, música en vivo y clases maestras con chefs reconocidos...',
    'Información',
    '30 de Enero, 2026',
    '11:30',
    'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80',
    'Ana Torres',
    ARRAY['Cultura', 'Gastronomía', 'Eventos'],
    false,
    false,
    'published',
    '[]'::jsonb
  ),
  (
    'Mercados Globales Cierran con Pérdidas',
    'Incertidumbre por conflictos internacionales',
    'Las bolsas de Nueva York y Londres registraron caídas significativas hoy. Expertos advierten sobre una posible recesión si la situación geopolítica no mejora...',
    'Internacionales',
    '29 de Enero, 2026',
    '16:10',
    'https://images.unsplash.com/photo-1611974765270-ca12586343bb?auto=format&fit=crop&q=80',
    'Roberto Díaz',
    ARRAY['Finanzas', 'Mundo', 'Bolsa'],
    false,
    false,
    'published',
    '[]'::jsonb
  ),
  (
    'Alerta Ambiental: Derrame de Petróleo',
    'Controlan fuga en oleoducto tras 48 horas',
    'Equipos de emergencia lograron contener el vertido que amenazaba un río local. Autoridades investigan las causas y anuncian sanciones severas...',
    'Región',
    '28 de Enero, 2026',
    '07:45',
    'https://images.unsplash.com/photo-1611273426761-53c8577a3c7f?auto=format&fit=crop&q=80',
    'Investigación',
    ARRAY['Ambiente', 'Denuncia', 'Región'],
    false,
    true,
    'published',
    '[]'::jsonb
  );
